// mobile/src/components/favourite/FavouriteEditorDialog.tsx
import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';

import { Dialog } from '@/components/design-system/feedback/Dialog';
import { useToast } from '@/components/design-system/feedback/ToastProvider';
import { Button } from '@/components/design-system/forms/Button';
import { Input } from '@/components/design-system/forms/Input';
import { RatingStars } from '@/components/favourite/RatingStars';
import { useFavourites } from '@/hooks/useFavourites';
import { useUpsertFavourite } from '@/hooks/useUpsertFavourite';
import { colors, fonts, spacing, typography } from '@/theme/tokens';

export interface FavouriteEditorDialogProps {
  open: boolean;
  onClose: () => void;
  restaurantId: string;
}

/** Mirrors the backend [Range(1,5)] validation before the API call. */
function isValidRating(rating: number): boolean {
  return Number.isInteger(rating) && rating >= 1 && rating <= 5;
}

/**
 * Rate a restaurant 1-5 with an optional note. Seeds its fields from the
 * restaurant's existing favourite on open, validates the rating client-side,
 * upserts via `useUpsertFavourite`, and confirms success or surfaces an error
 * via a toast. On error the dialog stays open for a retry.
 */
export function FavouriteEditorDialog({
  open,
  onClose,
  restaurantId,
}: FavouriteEditorDialogProps): React.ReactElement {
  const { favouriteFor } = useFavourites();
  const upsert = useUpsertFavourite();
  const { push } = useToast();

  const [rating, setRating] = useState(0);
  const [note, setNote] = useState('');

  // Seed the form from the existing favourite each time the dialog opens.
  useEffect(() => {
    if (open) {
      const existing = favouriteFor(restaurantId);
      setRating(existing?.rating ?? 0);
      setNote(existing?.note ?? '');
    }
  }, [open, restaurantId, favouriteFor]);

  const valid = isValidRating(rating);

  function handleSave() {
    if (!valid || upsert.isPending) return;
    upsert.mutate(
      { restaurantId, rating, note: note.trim() || null },
      {
        onSuccess: () => {
          push({ title: 'Rating saved', tone: 'success' });
          onClose();
        },
        onError: () => {
          push({
            title: 'Could not save rating',
            description: 'Please try again.',
            tone: 'danger',
          });
        },
      },
    );
  }

  return (
    <Dialog
      open={open}
      onClose={onClose}
      title="Rate restaurant"
      footer={
        <>
          <Button variant="ghost" onPress={onClose}>
            Cancel
          </Button>
          <Button
            variant="primary"
            onPress={handleSave}
            disabled={!valid}
            loading={upsert.isPending}
          >
            Save
          </Button>
        </>
      }
    >
      <View style={styles.field}>
        <Text style={styles.label}>Rating</Text>
        <RatingStars value={rating} editable size={28} onChange={setRating} />
      </View>
      <Input
        label="Note"
        placeholder="Optional"
        value={note}
        onChangeText={setNote}
        multiline
        rows={3}
      />
    </Dialog>
  );
}

const styles = StyleSheet.create({
  field: {
    gap: spacing[2],
  },
  label: {
    fontFamily: fonts.bodyMedium,
    fontSize: typography.size.xs,
    fontWeight: typography.weight.medium,
    color: colors.textSecondary,
  },
});

// frontend/src/components/favourite/FavouriteEditorDialog.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import Dialog from '../design-system/feedback/Dialog.vue'
import Input from '../design-system/forms/Input.vue'
import Button from '../design-system/forms/Button.vue'
import RatingStars from './RatingStars.vue'
import { useFavouritesStore } from '../../stores/favourites'
import { useToastsStore } from '../../stores/toasts'

const props = defineProps<{ open: boolean; restaurantId: string }>()
const emit = defineEmits<{ close: [] }>()

const favourites = useFavouritesStore()
const toasts = useToastsStore()

const rating = ref(0)
const note = ref('')
const saving = ref(false)

// Seed the form from the existing favourite each time the dialog opens.
watch(
  () => props.open,
  (open) => {
    if (!open) return
    const existing = favourites.favouriteFor(props.restaurantId)
    rating.value = existing?.rating ?? 0
    note.value = existing?.note ?? ''
  },
)

// Mirror the backend [Range(1,5)] validation before calling the API.
const valid = computed(
  () => Number.isInteger(rating.value) && rating.value >= 1 && rating.value <= 5,
)

async function save(): Promise<void> {
  if (!valid.value || saving.value) return
  saving.value = true
  try {
    await favourites.upsert(props.restaurantId, rating.value, note.value.trim() || null)
    toasts.push({ title: 'Rating saved', tone: 'success' })
    emit('close')
  } catch {
    toasts.push({
      title: 'Could not save rating',
      description: 'Please try again.',
      tone: 'danger',
    })
  } finally {
    saving.value = false
  }
}
</script>

<template>
  <Dialog :open="open" title="Rate restaurant" @close="emit('close')">
    <div class="fav-editor">
      <div class="fav-editor__field">
        <span class="fav-editor__label">Rating</span>
        <RatingStars v-model="rating" editable :size="24" />
      </div>
      <Input v-model="note" label="Note" placeholder="Optional" multiline :rows="3" />
    </div>

    <template #footer>
      <Button variant="ghost" @click="emit('close')">Cancel</Button>
      <Button variant="primary" :disabled="!valid" :loading="saving" @click="save">Save</Button>
    </template>
  </Dialog>
</template>

<style scoped>
.fav-editor {
  display: flex;
  flex-direction: column;
  gap: var(--space-5);
}

.fav-editor__field {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
}

.fav-editor__label {
  font-family: var(--font-body);
  font-size: var(--text-xs);
  font-weight: var(--weight-medium);
  color: var(--text-secondary);
}
</style>
