// frontend/src/components/restaurant/RestaurantCard.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import Card from '../design-system/data-display/Card.vue'
import Badge from '../design-system/data-display/Badge.vue'
import Tag from '../design-system/data-display/Tag.vue'
import Button from '../design-system/forms/Button.vue'
import OfferList from './OfferList.vue'
import RatingStars from '../favourite/RatingStars.vue'
import FavouriteEditorDialog from '../favourite/FavouriteEditorDialog.vue'
import { useRestaurantsStore } from '../../stores/restaurants'
import { useEnvironmentsStore } from '../../stores/environments'
import { useFavouritesStore } from '../../stores/favourites'
import type { Restaurant } from '../../types/restaurant'

const props = defineProps<{ restaurant: Restaurant }>()
const store = useRestaurantsStore()
const environments = useEnvironmentsStore()
const favourites = useFavouritesStore()

// Expansion is local view state; the store owns only fetched data.
const expanded = ref(false)
const editorOpen = ref(false)

const favourite = computed(() => favourites.favouriteFor(props.restaurant.id))

const entry = computed(() => store.offersFor(props.restaurant.id))
const noOffers = computed(() => {
  if (!props.restaurant.hasOffers) return true
  const e = entry.value
  return Boolean(e && e.loaded && e.offers.length === 0)
})

// The membership action only appears when a specific environment (not "All") is selected.
const showMembership = computed(() => environments.selectedEnvironmentId !== null)
const isMember = computed(() => environments.isMember(props.restaurant.id))
const membershipPending = computed(() => environments.isPending(props.restaurant.id))

async function toggleOffers(): Promise<void> {
  expanded.value = !expanded.value
  if (expanded.value) {
    await store.loadOffers(props.restaurant.id)
  }
}

async function toggleMembership(): Promise<void> {
  if (isMember.value) {
    await environments.removeRestaurant(props.restaurant.id)
  } else {
    await environments.addRestaurant(props.restaurant.id)
  }
}
</script>

<template>
  <Card>
    <div class="restaurant__head">
      <div class="restaurant__titles">
        <h2 class="restaurant__name">{{ restaurant.name }}</h2>
        <Tag>{{ restaurant.city }}</Tag>
      </div>
      <div class="restaurant__badges">
        <Badge v-if="restaurant.isFastFood" tone="accent">Fast food</Badge>
        <Badge v-if="noOffers" tone="neutral">No offers today</Badge>
      </div>
    </div>

    <RatingStars v-if="favourite" class="restaurant__rating" :model-value="favourite.rating" />

    <dl class="restaurant__meta">
      <div class="restaurant__row">
        <dt>Offer time</dt>
        <dd>{{ restaurant.offerTimeText }}</dd>
      </div>
      <div class="restaurant__row">
        <dt>Parking</dt>
        <dd>{{ restaurant.parkingInfo }}</dd>
      </div>
      <div class="restaurant__row">
        <dt>Opening</dt>
        <dd>{{ restaurant.openingInfo }}</dd>
      </div>
    </dl>

    <div class="restaurant__actions">
      <Button
        variant="secondary"
        size="sm"
        :icon="expanded ? 'chevron-up' : 'chevron-down'"
        iconPosition="right"
        @click="toggleOffers"
      >
        {{ expanded ? 'Hide offers' : 'See offers' }}
      </Button>

      <Button
        v-if="showMembership"
        :variant="isMember ? 'ghost' : 'secondary'"
        size="sm"
        :icon="isMember ? 'minus' : 'plus'"
        :loading="membershipPending"
        @click="toggleMembership"
      >
        {{ isMember ? 'Remove from environment' : 'Add to environment' }}
      </Button>

      <Button variant="ghost" size="sm" @click="editorOpen = true">
        {{ favourite ? 'Edit rating' : 'Rate' }}
      </Button>
    </div>

    <OfferList v-if="expanded" :restaurant-id="restaurant.id" />

    <FavouriteEditorDialog
      :open="editorOpen"
      :restaurant-id="restaurant.id"
      @close="editorOpen = false"
    />
  </Card>
</template>

<style scoped>
.restaurant__head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--space-4);
  margin-bottom: var(--space-4);
}

.restaurant__titles {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: var(--space-3);
}

.restaurant__name {
  margin: 0;
  font-family: var(--font-display);
  font-size: var(--text-lg);
  font-weight: var(--weight-semibold);
  letter-spacing: var(--tracking-tight);
  color: var(--text-primary);
}

.restaurant__badges {
  display: flex;
  flex-shrink: 0;
  flex-wrap: wrap;
  gap: var(--space-2);
}

.restaurant__meta {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
  margin: 0 0 var(--space-5);
}

.restaurant__rating {
  margin-bottom: var(--space-4);
}

.restaurant__actions {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-2);
}

.restaurant__row {
  display: flex;
  gap: var(--space-4);
  font-size: var(--text-sm);
}

.restaurant__row dt {
  flex-shrink: 0;
  width: 88px;
  color: var(--text-secondary);
}

.restaurant__row dd {
  margin: 0;
  color: var(--text-primary);
}
</style>

// mobile/src/components/restaurant/RestaurantCard.tsx
import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { Badge } from '@/components/design-system/data-display/Badge';
import { Card } from '@/components/design-system/data-display/Card';
import { Tag } from '@/components/design-system/data-display/Tag';
import { Button } from '@/components/design-system/forms/Button';
import { Icon } from '@/components/design-system/icons/Icon';
import { FavouriteEditorDialog } from '@/components/favourite/FavouriteEditorDialog';
import { RatingStars } from '@/components/favourite/RatingStars';
import { OfferList } from '@/components/restaurant/OfferList';
import { useRestaurantOffers } from '@/hooks/useRestaurantOffers';
import {
  useAddRestaurantToEnvironment,
  useRemoveRestaurantFromEnvironment,
} from '@/hooks/useEnvironmentMutations';
import type { MembershipEntry } from '@/hooks/useEnvironmentRestaurants';
import type { Favourite } from '@/types/favourite';
import type { Restaurant } from '@/types/restaurant';
import { colors, fonts, spacing, typography } from '@/theme/tokens';

export interface RestaurantCardProps {
  restaurant: Restaurant;
  expanded: boolean;
  onToggle: () => void;
  /** The environment the list is filtered to, or `null` for "All". */
  selectedEnvironmentId?: string | null;
  /** This restaurant's membership in the selected environment, if any. */
  membershipEntry?: MembershipEntry;
  /** This restaurant's favourite (rating + note), if the user has one. */
  favourite?: Favourite;
}

/**
 * Presentational restaurant card: name, city Tag, a "Fast food" Badge and a
 * "No offers today" Badge (from the static `hasOffers` hint or a resolved-empty
 * offers query), and an expand affordance that reveals the OfferList. Reading
 * the offers query here is deduped with OfferList's own use of it.
 *
 * The card always shows a favourite surface: read-only stars when a favourite
 * exists plus a "Rate" / "Edit rating" action opening the editor. When a
 * specific environment is selected (not "All"), it also shows an
 * "Add to / Remove from environment" action reflecting current membership.
 */
export function RestaurantCard({
  restaurant,
  expanded,
  onToggle,
  selectedEnvironmentId = null,
  membershipEntry,
  favourite,
}: RestaurantCardProps): React.ReactElement {
  // Enabled only when expanded; shares the cache entry with OfferList.
  const { data: offers } = useRestaurantOffers(restaurant.id, expanded);
  const resolvedEmpty = offers != null && offers.length === 0;
  const noOffersToday = !restaurant.hasOffers || resolvedEmpty;

  const [editorOpen, setEditorOpen] = useState(false);

  const addMembership = useAddRestaurantToEnvironment();
  const removeMembership = useRemoveRestaurantFromEnvironment();
  const isMember = membershipEntry != null;
  const membershipPending = addMembership.isPending || removeMembership.isPending;

  function toggleMembership() {
    if (selectedEnvironmentId == null) return;
    if (membershipEntry) {
      removeMembership.mutate({
        joinId: membershipEntry.joinId,
        concurrencyToken: membershipEntry.concurrencyToken,
      });
    } else {
      addMembership.mutate({ environmentId: selectedEnvironmentId, restaurantId: restaurant.id });
    }
  }

  return (
    <Card padding={spacing[4]}>
      <Pressable
        onPress={onToggle}
        accessibilityRole="button"
        accessibilityState={{ expanded }}
        accessibilityLabel={restaurant.name}
        style={styles.header}
      >
        <View style={styles.headerText}>
          <Text style={styles.name}>{restaurant.name}</Text>
          <View style={styles.meta}>
            <Tag>{restaurant.city}</Tag>
            {restaurant.isFastFood && <Badge tone="neutral">Fast food</Badge>}
            {noOffersToday && <Badge tone="warning">No offers today</Badge>}
          </View>
        </View>
        <Icon
          name={expanded ? 'chevron-up' : 'chevron-down'}
          size={18}
          color={colors.textSecondary}
        />
      </Pressable>

      <View style={styles.favouriteRow}>
        {favourite && <RatingStars value={favourite.rating} size={16} />}
        <Button
          variant="ghost"
          size="sm"
          onPress={() => setEditorOpen(true)}
          accessibilityLabel={favourite ? 'Edit rating' : 'Rate'}
        >
          {favourite ? 'Edit rating' : 'Rate'}
        </Button>
      </View>

      {selectedEnvironmentId != null && (
        <View style={styles.actionRow}>
          <Button
            variant={isMember ? 'secondary' : 'ghost'}
            size="sm"
            icon={isMember ? 'minus' : 'plus'}
            onPress={toggleMembership}
            loading={membershipPending}
            accessibilityLabel={isMember ? 'Remove from environment' : 'Add to environment'}
          >
            {isMember ? 'Remove from environment' : 'Add to environment'}
          </Button>
        </View>
      )}

      {expanded && <OfferList restaurantId={restaurant.id} />}

      {editorOpen && (
        <FavouriteEditorDialog
          open
          onClose={() => setEditorOpen(false)}
          restaurantId={restaurant.id}
        />
      )}
    </Card>
  );
}

const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing[3],
  },
  headerText: {
    flex: 1,
    gap: spacing[2],
  },
  name: {
    fontFamily: fonts.display,
    fontSize: typography.size.md,
    fontWeight: typography.weight.semibold,
    color: colors.textPrimary,
  },
  meta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing[2],
  },
  favouriteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    marginTop: spacing[3],
  },
  actionRow: {
    flexDirection: 'row',
    marginTop: spacing[3],
  },
});
