// mobile/src/components/design-system/forms/Button.tsx
import React from 'react';
import {
  ActivityIndicator,
  Pressable,
  StyleProp,
  StyleSheet,
  Text,
  ViewStyle,
} from 'react-native';

import { Icon, IconName } from '@/components/design-system/icons/Icon';
import { colors, fonts, radius, typography } from '@/theme/tokens';

/** Props ported 1:1 from Button.d.ts; web `onClick`/`type` become `onPress`. */
export interface ButtonProps {
  children?: React.ReactNode;
  /** Visual style. Default "primary". */
  variant?: 'primary' | 'secondary' | 'ghost' | 'danger';
  /** Default "md". */
  size?: 'sm' | 'md' | 'lg';
  /** Optional leading/trailing icon glyph. */
  icon?: IconName;
  iconPosition?: 'left' | 'right';
  /** Shows spinner in place of icon, disables interaction. */
  loading?: boolean;
  disabled?: boolean;
  fullWidth?: boolean;
  onPress?: () => void;
  style?: StyleProp<ViewStyle>;
  accessibilityLabel?: string;
}

type SizeSpec = {
  padY: number;
  padX: number;
  fontSize: number;
  gap: number;
  iconSize: number;
  radius: number;
};

const SIZE: Record<NonNullable<ButtonProps['size']>, SizeSpec> = {
  sm: { padY: 6, padX: 10, fontSize: typography.size.xs, gap: 6, iconSize: 14, radius: radius.sm },
  md: { padY: 9, padX: 14, fontSize: typography.size.sm, gap: 7, iconSize: 15, radius: radius.md },
  lg: { padY: 12, padX: 18, fontSize: typography.size.base, gap: 8, iconSize: 16, radius: radius.md },
};

type VariantSpec = { base: string; press: string; text: string; border: string };

function variantStyle(variant: NonNullable<ButtonProps['variant']>): VariantSpec {
  switch (variant) {
    case 'secondary':
      return {
        base: colors.surfaceCard,
        press: colors.neutral4,
        text: colors.textPrimary,
        border: colors.borderSubtle,
      };
    case 'ghost':
      return {
        base: 'transparent',
        press: colors.neutral4,
        text: colors.textPrimary,
        border: 'transparent',
      };
    case 'danger':
      return {
        base: colors.statusDangerBg,
        press: colors.statusDangerBg,
        text: colors.statusDanger,
        border: colors.statusDangerBg,
      };
    default:
      return {
        base: colors.actionPrimary,
        press: colors.actionPrimaryPress,
        text: colors.actionPrimaryText,
        border: 'transparent',
      };
  }
}

export function Button({
  children,
  variant = 'primary',
  size = 'md',
  icon,
  iconPosition = 'left',
  loading = false,
  disabled = false,
  fullWidth = false,
  onPress,
  style,
  accessibilityLabel,
}: ButtonProps): React.ReactElement {
  const s = SIZE[size] ?? SIZE.md;
  const v = variantStyle(variant);
  const isDisabled = disabled || loading;

  return (
    <Pressable
      onPress={onPress}
      disabled={isDisabled}
      accessibilityRole="button"
      accessibilityState={{ disabled: isDisabled, busy: loading }}
      accessibilityLabel={accessibilityLabel}
      style={({ pressed }) => [
        styles.base,
        {
          width: fullWidth ? '100%' : undefined,
          gap: s.gap,
          paddingVertical: s.padY,
          paddingHorizontal: s.padX,
          borderRadius: s.radius,
          borderColor: isDisabled ? colors.borderSubtle : v.border,
          backgroundColor: isDisabled
            ? colors.neutral2
            : pressed
              ? v.press
              : v.base,
        },
        style,
      ]}
    >
      {loading ? (
        <ActivityIndicator size="small" color={isDisabled ? colors.textDisabled : v.text} />
      ) : (
        icon &&
        iconPosition === 'left' && (
          <Icon name={icon} size={s.iconSize} color={isDisabled ? colors.textDisabled : v.text} />
        )
      )}
      {children != null && (
        <Text
          style={[
            styles.label,
            { fontSize: s.fontSize, color: isDisabled ? colors.textDisabled : v.text },
          ]}
        >
          {children}
        </Text>
      )}
      {!loading && icon && iconPosition === 'right' && (
        <Icon name={icon} size={s.iconSize} color={isDisabled ? colors.textDisabled : v.text} />
      )}
    </Pressable>
  );
}

const styles = StyleSheet.create({
  base: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  } as ViewStyle,
  label: {
    fontFamily: fonts.bodyMedium,
    fontWeight: typography.weight.medium,
    letterSpacing: 0,
  },
});

// frontend/src/components/design-system/forms/Button.vue
<script setup lang="ts">
import { computed, useSlots } from 'vue'
import Icon, { type IconName } from '../Icon.vue'

// Prop contract ported 1:1 from the design system's Button.d.ts.
const props = withDefaults(
  defineProps<{
    /** Visual style. Default "primary". */
    variant?: 'primary' | 'secondary' | 'ghost' | 'danger'
    /** Default "md". */
    size?: 'sm' | 'md' | 'lg'
    /** Optional leading/trailing icon glyph. */
    icon?: IconName
    iconPosition?: 'left' | 'right'
    /** Shows spinner in place of icon, disables interaction. */
    loading?: boolean
    disabled?: boolean
    fullWidth?: boolean
    type?: 'button' | 'submit' | 'reset'
  }>(),
  {
    variant: 'primary',
    size: 'md',
    iconPosition: 'left',
    loading: false,
    disabled: false,
    fullWidth: false,
    type: 'button',
  },
)

const emit = defineEmits<{ click: [e: MouseEvent] }>()

const slots = useSlots()
const hasLabel = computed(() => !!slots.default)

const isDisabled = computed(() => props.disabled || props.loading)

// Icon pixel size per button size, matching the design system's SIZE map.
const iconSize = computed(() => (props.size === 'sm' ? 14 : props.size === 'lg' ? 16 : 15))

function onClick(e: MouseEvent) {
  if (isDisabled.value) return
  emit('click', e)
}
</script>

<template>
  <button
    :type="type"
    :disabled="isDisabled"
    class="ds-button"
    :class="[`ds-button--${variant}`, `ds-button--${size}`, { 'ds-button--full': fullWidth }]"
    @click="onClick"
  >
    <Icon v-if="loading" name="spinner" :size="iconSize" />
    <Icon
      v-else-if="icon && iconPosition === 'left'"
      :name="icon"
      :size="iconSize"
    />
    <span v-if="hasLabel"><slot /></span>
    <Icon
      v-if="!loading && icon && iconPosition === 'right'"
      :name="icon"
      :size="iconSize"
    />
  </button>
</template>

<style scoped>
.ds-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  font-family: var(--font-body);
  font-weight: var(--weight-medium);
  letter-spacing: var(--tracking-normal);
  cursor: pointer;
  transition:
    background var(--duration-fast) var(--ease-standard),
    border-color var(--duration-fast) var(--ease-standard);
}

.ds-button--full {
  width: 100%;
}

/* ---- Sizes ---- */
.ds-button--sm {
  gap: 6px;
  padding: 6px 10px;
  font-size: var(--text-xs);
  border-radius: var(--radius-sm);
}

.ds-button--md {
  gap: 7px;
  padding: 9px 14px;
  font-size: var(--text-sm);
  border-radius: var(--radius-md);
}

.ds-button--lg {
  gap: 8px;
  padding: 12px 18px;
  font-size: var(--text-base);
  border-radius: var(--radius-md);
}

/* ---- Variants ---- */
.ds-button--primary {
  color: var(--action-primary-text);
  background: var(--action-primary);
  border: 1px solid transparent;
}

.ds-button--primary:hover:not(:disabled) {
  background: var(--action-primary-hover);
}

.ds-button--primary:active:not(:disabled) {
  background: var(--action-primary-press);
}

.ds-button--secondary {
  color: var(--text-primary);
  background: var(--surface-card);
  border: 1px solid var(--border-subtle);
}

.ds-button--secondary:hover:not(:disabled) {
  background: var(--surface-hover);
}

.ds-button--secondary:active:not(:disabled) {
  background: var(--neutral-4);
}

.ds-button--ghost {
  color: var(--text-primary);
  background: transparent;
  border: 1px solid transparent;
}

.ds-button--ghost:hover:not(:disabled) {
  background: var(--surface-hover);
}

.ds-button--ghost:active:not(:disabled) {
  background: var(--neutral-4);
}

.ds-button--danger {
  color: var(--status-danger);
  background: var(--status-danger-bg);
  border: 1px solid var(--status-danger-bg);
}

.ds-button--danger:hover:not(:disabled) {
  background: var(--status-danger-bg);
}

.ds-button--danger:active:not(:disabled) {
  background: var(--status-danger-bg);
}

/* ---- Focus ---- */
.ds-button:focus-visible {
  outline: none;
  box-shadow: var(--shadow-focus-ring);
}

/* ---- Disabled ---- */
.ds-button:disabled {
  color: var(--text-disabled);
  background: var(--neutral-2);
  border: 1px solid var(--border-subtle);
  cursor: not-allowed;
}
</style>
