// mobile/src/components/design-system/data-display/Badge.tsx
import React from 'react';
import { StyleProp, StyleSheet, Text, View, ViewStyle } from 'react-native';

import { Icon, IconName } from '@/components/design-system/icons/Icon';
import { colors, fonts, radius, typography } from '@/theme/tokens';

/** Ported 1:1 from the design system Badge — an uppercase mono status label. */
export type BadgeTone = 'neutral' | 'accent' | 'success' | 'warning' | 'danger';

export interface BadgeProps {
  children?: React.ReactNode;
  /** Semantic tone. Default "neutral". */
  tone?: BadgeTone;
  /** Optional leading icon glyph, colored to the tone foreground. */
  icon?: IconName;
  style?: StyleProp<ViewStyle>;
}

const TONE: Record<BadgeTone, { bg: string; fg: string }> = {
  neutral: { bg: colors.neutral3, fg: colors.textPrimary },
  accent: { bg: colors.accent2, fg: colors.accent9 },
  success: { bg: colors.statusSuccessBg, fg: colors.statusSuccess },
  warning: { bg: colors.statusWarningBg, fg: colors.statusWarning },
  danger: { bg: colors.statusDangerBg, fg: colors.statusDanger },
};

export function Badge({
  children,
  tone = 'neutral',
  icon,
  style,
}: BadgeProps): React.ReactElement {
  const t = TONE[tone] ?? TONE.neutral;
  return (
    <View style={[styles.badge, { backgroundColor: t.bg }, style]}>
      {icon && <Icon name={icon} size={10} color={t.fg} />}
      {children != null && <Text style={[styles.label, { color: t.fg }]}>{children}</Text>}
    </View>
  );
}

const styles = StyleSheet.create({
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 4,
    borderRadius: radius.sm,
    paddingVertical: 3,
    paddingHorizontal: 7,
  },
  label: {
    fontFamily: fonts.mono,
    fontSize: typography.size['2xs'],
    fontWeight: typography.weight.medium,
    // tracking-wide (0.04em) * 11px font size.
    letterSpacing: 0.44,
    textTransform: 'uppercase',
  },
});

// frontend/src/components/design-system/data-display/Badge.vue
<script setup lang="ts">
import Icon, { type IconName } from '../Icon.vue'

// Prop contract ported 1:1 from the design system's Badge.d.ts.
withDefaults(
  defineProps<{
    tone?: 'neutral' | 'accent' | 'success' | 'warning' | 'danger'
    icon?: IconName
  }>(),
  {
    tone: 'neutral',
  },
)
</script>

<template>
  <span class="ds-badge" :class="`ds-badge--${tone}`">
    <Icon v-if="icon" :name="icon" :size="10" />
    <slot />
  </span>
</template>

<style scoped>
.ds-badge {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 3px 7px;
  font-family: var(--font-mono);
  font-size: var(--text-2xs);
  font-weight: var(--weight-medium);
  letter-spacing: var(--tracking-wide);
  /* Deliberate uppercase treatment - the one sanctioned exception to sentence case. */
  text-transform: uppercase;
  border-radius: var(--radius-sm);
}

.ds-badge--neutral {
  color: var(--text-primary);
  background: var(--neutral-3);
}

.ds-badge--accent {
  color: var(--accent-9);
  background: var(--accent-2);
}

.ds-badge--success {
  color: var(--status-success);
  background: var(--status-success-bg);
}

.ds-badge--warning {
  color: var(--status-warning);
  background: var(--status-warning-bg);
}

.ds-badge--danger {
  color: var(--status-danger);
  background: var(--status-danger-bg);
}
</style>
