// mobile/src/components/design-system/data-display/Tag.tsx
import React from 'react';
import { Pressable, StyleProp, StyleSheet, Text, View, ViewStyle } from 'react-native';

import { Icon } from '@/components/design-system/icons/Icon';
import { colors, fonts, radius, typography } from '@/theme/tokens';

/**
 * Ported 1:1 from the design system Tag — a full-pill chip for user-facing
 * categorization. `selected` gives the accent-tinted filter look; `onRemove`
 * adds a trailing pressable x.
 */
export interface TagProps {
  children?: React.ReactNode;
  /** Accent-tinted "selected" look, e.g. an active filter. Default false. */
  selected?: boolean;
  /** When set, renders a trailing x that calls this. */
  onRemove?: () => void;
  style?: StyleProp<ViewStyle>;
}

export function Tag({
  children,
  selected = false,
  onRemove,
  style,
}: TagProps): React.ReactElement {
  const fg = selected ? colors.accent9 : colors.textPrimary;
  return (
    <View
      style={[
        styles.tag,
        {
          backgroundColor: selected ? colors.accent2 : colors.surfaceHover,
          borderColor: selected ? colors.accent3 : colors.borderSubtle,
        },
        style,
      ]}
    >
      {children != null && <Text style={[styles.label, { color: fg }]}>{children}</Text>}
      {onRemove && (
        <Pressable
          onPress={onRemove}
          accessibilityRole="button"
          accessibilityLabel="Remove"
          hitSlop={6}
          style={styles.remove}
        >
          <Icon name="x" size={11} color={fg} />
        </Pressable>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    borderWidth: 1,
    borderRadius: radius.full,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  label: {
    fontFamily: fonts.bodyMedium,
    fontSize: typography.size.xs,
    fontWeight: typography.weight.medium,
  },
  remove: {
    opacity: 0.7,
  },
});

// frontend/src/components/design-system/data-display/Tag.vue
<script setup lang="ts">
import Icon from '../Icon.vue'

// Ported from the design system's Tag.d.ts. React's `onRemove` callback is
// translated the Vue-idiomatic way: a `removable` prop shows the remove
// affordance and a native `remove` event is emitted (analogous to Button's
// onClick -> @click).
withDefaults(
  defineProps<{
    /** Accent-tinted "selected" look, e.g. active filter. */
    selected?: boolean
    /** Shows an x that emits `remove` when clicked (removable chip). */
    removable?: boolean
  }>(),
  {
    selected: false,
    removable: false,
  },
)

const emit = defineEmits<{ remove: [] }>()
</script>

<template>
  <span class="ds-tag" :class="{ 'ds-tag--selected': selected }">
    <slot />
    <button
      v-if="removable"
      type="button"
      class="ds-tag__remove"
      aria-label="Remove"
      @click="emit('remove')"
    >
      <Icon name="x" :size="11" />
    </button>
  </span>
</template>

<style scoped>
.ds-tag {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 4px 10px;
  font-family: var(--font-body);
  font-size: var(--text-xs);
  font-weight: var(--weight-medium);
  color: var(--text-primary);
  background: var(--surface-hover);
  border: 1px solid var(--border-subtle);
  border-radius: var(--radius-full);
}

.ds-tag--selected {
  color: var(--accent-9);
  background: var(--accent-2);
  border-color: var(--accent-3);
}

.ds-tag__remove {
  display: flex;
  align-items: center;
  padding: 0;
  color: inherit;
  background: none;
  border: none;
  cursor: pointer;
  opacity: 0.7;
}

.ds-tag__remove:hover {
  opacity: 1;
}
</style>
