// mobile/src/components/wheel/WheelSpinner.tsx
import React, { useMemo, useRef, useState } from 'react';
import { Animated, Easing, StyleSheet, Text, View } from 'react-native';
import Svg, { Circle, G, Path, Text as SvgText } from 'react-native-svg';

import { Button } from '@/components/design-system/forms/Button';
import { colors, fonts, radius, spacing, typography } from '@/theme/tokens';

export interface WheelSpinnerProps {
  names: string[];
  /** Called with the chosen name when a spin settles. */
  onResult?: (name: string) => void;
}

const SIZE = 260;
const VIEW = 200;
const CENTER = 100;
const RADIUS = 92;
const LABEL_RADIUS = 60;

// Token-only segment palette (no hardcoded colors), cycled by index.
const PALETTE = [
  colors.accent7,
  colors.statusSuccess,
  colors.statusWarning,
  colors.statusDanger,
  colors.accent5,
  colors.neutral5,
];

function pointAt(angleDeg: number, r: number): [number, number] {
  const rad = (angleDeg * Math.PI) / 180;
  // Angle measured clockwise from the top (12 o'clock).
  return [CENTER + r * Math.sin(rad), CENTER - r * Math.cos(rad)];
}

/**
 * Native spinning wheel. Mirrors the web spinner's geometry (one SVG arc
 * segment per name, token-cycled palette) but rotates an Animated layer holding
 * the segments while the pointer and hub stay static on top. `spin()` picks a
 * name client-side and animates a multi-turn ease-out landing that segment
 * under the top pointer, then reports the winner. Needs at least 2 names.
 */
export function WheelSpinner({ names, onResult }: WheelSpinnerProps): React.ReactElement {
  const rotation = useRef(new Animated.Value(0)).current;
  const rotationDeg = useRef(0);
  const [spinning, setSpinning] = useState(false);
  const [result, setResult] = useState<string | null>(null);

  const canSpin = names.length >= 2 && !spinning;

  const segments = useMemo(() => {
    const n = names.length;
    const seg = 360 / n;
    return names.map((name, i) => {
      const [x1, y1] = pointAt(i * seg, RADIUS);
      const [x2, y2] = pointAt((i + 1) * seg, RADIUS);
      const largeArc = seg > 180 ? 1 : 0;
      const [lx, ly] = pointAt(i * seg + seg / 2, LABEL_RADIUS);
      return {
        name,
        path: `M ${CENTER} ${CENTER} L ${x1} ${y1} A ${RADIUS} ${RADIUS} 0 ${largeArc} 1 ${x2} ${y2} Z`,
        color: PALETTE[i % PALETTE.length],
        label: name.length > 12 ? `${name.slice(0, 11)}…` : name,
        lx,
        ly,
      };
    });
  }, [names]);

  // A single interpolation maps any absolute degree value to a rotate string
  // (linear extrapolation extends past 360), so multi-turn targets just work.
  const rotate = rotation.interpolate({
    inputRange: [0, 360],
    outputRange: ['0deg', '360deg'],
  });

  function spin() {
    if (!canSpin) return;
    const n = names.length;
    const chosen = Math.floor(Math.random() * n);
    const seg = 360 / n;
    const center = (chosen + 0.5) * seg;
    // Land the chosen segment's centre under the top pointer: rotation ≡ -center (mod 360).
    const currentMod = ((rotationDeg.current % 360) + 360) % 360;
    const desiredMod = (((-center) % 360) + 360) % 360;
    let delta = desiredMod - currentMod;
    if (delta < 0) delta += 360;
    const target = rotationDeg.current + delta + 360 * 5;
    rotationDeg.current = target;

    setResult(null);
    setSpinning(true);
    Animated.timing(rotation, {
      toValue: target,
      duration: 3200,
      easing: Easing.out(Easing.cubic),
      useNativeDriver: true,
    }).start(() => {
      setSpinning(false);
      setResult(names[chosen]);
      onResult?.(names[chosen]);
    });
  }

  return (
    <View style={styles.container}>
      <View style={styles.wheelWrap}>
        <View style={styles.pointer} />
        <Animated.View style={{ transform: [{ rotate }] }}>
          <Svg width={SIZE} height={SIZE} viewBox={`0 0 ${VIEW} ${VIEW}`}>
            {segments.map((s) => (
              <G key={s.name}>
                <Path d={s.path} fill={s.color} stroke={colors.surfaceApp} strokeWidth={1} />
                <SvgText
                  x={s.lx}
                  y={s.ly}
                  fill={colors.textOnAccent}
                  fontSize={7}
                  fontFamily={fonts.bodySemibold}
                  textAnchor="middle"
                  alignmentBaseline="middle"
                >
                  {s.label}
                </SvgText>
              </G>
            ))}
          </Svg>
        </Animated.View>
        {/* Static rim + hub drawn over the rotor. */}
        <Svg width={SIZE} height={SIZE} viewBox={`0 0 ${VIEW} ${VIEW}`} style={StyleSheet.absoluteFill}>
          <Circle cx={CENTER} cy={CENTER} r={93} fill="none" stroke={colors.borderSubtle} strokeWidth={2} />
          <Circle cx={CENTER} cy={CENTER} r={10} fill={colors.surfaceRaised} stroke={colors.borderStrong} strokeWidth={1.5} />
          <Circle cx={CENTER} cy={CENTER} r={3.5} fill={colors.accent7} />
        </Svg>
      </View>

      <View style={styles.controls}>
        <Button variant="primary" onPress={spin} disabled={!canSpin} loading={spinning}>
          Spin
        </Button>
        {result ? (
          <View style={styles.result}>
            <Text style={styles.resultTag}>Winner</Text>
            <Text style={styles.resultName}>{result}</Text>
          </View>
        ) : names.length < 2 ? (
          <Text style={styles.hint}>Add at least 2 restaurants to spin.</Text>
        ) : null}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    gap: spacing[5],
  },
  wheelWrap: {
    width: SIZE,
    height: SIZE,
    maxWidth: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pointer: {
    position: 'absolute',
    top: -2,
    zIndex: 1,
    width: 0,
    height: 0,
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderTopWidth: 14,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: colors.textPrimary,
  },
  controls: {
    alignItems: 'center',
    gap: spacing[2],
  },
  result: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  resultTag: {
    paddingVertical: 2,
    paddingHorizontal: spacing[2],
    fontFamily: fonts.bodySemibold,
    fontSize: typography.size.xs,
    fontWeight: typography.weight.semibold,
    letterSpacing: typography.size.xs * typography.tracking.wide,
    color: colors.textOnAccent,
    backgroundColor: colors.accent7,
    borderRadius: radius.full,
    overflow: 'hidden',
  },
  resultName: {
    fontFamily: fonts.display,
    fontSize: typography.size.lg,
    fontWeight: typography.weight.semibold,
    color: colors.textPrimary,
  },
  hint: {
    fontFamily: fonts.body,
    fontSize: typography.size.sm,
    color: colors.textSecondary,
  },
});

// frontend/src/components/wheel/WheelSpinner.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import Button from '../design-system/forms/Button.vue'

const props = defineProps<{ names: string[] }>()
const emit = defineEmits<{ result: [name: string] }>()

// Token-only segment palette (no hardcoded colors), cycled by index.
const PALETTE = [
  'var(--accent-7)',
  'var(--status-success)',
  'var(--status-warning)',
  'var(--status-danger)',
  'var(--accent-5)',
  'var(--neutral-5)',
]

const CENTER = 100
const RADIUS = 92
const LABEL_RADIUS = 60

const rotation = ref(0)
const spinning = ref(false)
const result = ref<string | null>(null)
// Index of the settled winner, or null while idle/spinning. Drives dimming the other segments so
// the chosen one stands out under the pointer.
const winnerIndex = ref<number | null>(null)
let chosenIndex = 0

const canSpin = computed(() => props.names.length >= 2 && !spinning.value)

function pointAt(angleDeg: number, radius: number): [number, number] {
  const rad = (angleDeg * Math.PI) / 180
  // Angle measured clockwise from the top (12 o'clock).
  return [CENTER + radius * Math.sin(rad), CENTER - radius * Math.cos(rad)]
}

const segments = computed(() => {
  const n = props.names.length
  const seg = 360 / n
  return props.names.map((name, i) => {
    const a1 = i * seg
    const a2 = (i + 1) * seg
    const [x1, y1] = pointAt(a1, RADIUS)
    const [x2, y2] = pointAt(a2, RADIUS)
    const largeArc = seg > 180 ? 1 : 0
    const path = `M ${CENTER} ${CENTER} L ${x1} ${y1} A ${RADIUS} ${RADIUS} 0 ${largeArc} 1 ${x2} ${y2} Z`
    const [lx, ly] = pointAt(a1 + seg / 2, LABEL_RADIUS)
    return {
      index: i,
      name,
      path,
      color: PALETTE[i % PALETTE.length],
      label: name.length > 12 ? `${name.slice(0, 11)}…` : name,
      lx,
      ly,
    }
  })
})

function spin(): void {
  if (!canSpin.value) return
  const n = props.names.length
  // Clear the previous winner so all segments are lit again while the wheel turns.
  winnerIndex.value = null
  result.value = null
  chosenIndex = Math.floor(Math.random() * n)
  const seg = 360 / n
  const center = (chosenIndex + 0.5) * seg
  // Land the chosen segment's centre under the top pointer: rotation ≡ -center (mod 360).
  const currentMod = ((rotation.value % 360) + 360) % 360
  const desiredMod = (((-center) % 360) + 360) % 360
  let delta = desiredMod - currentMod
  if (delta < 0) delta += 360
  rotation.value = rotation.value + delta + 360 * 5
  spinning.value = true
}

function onTransitionEnd(): void {
  if (!spinning.value) return
  spinning.value = false
  winnerIndex.value = chosenIndex
  result.value = props.names[chosenIndex]
  emit('result', props.names[chosenIndex])
}
</script>

<template>
  <div class="spinner">
    <div class="spinner__wheel-wrap">
      <span class="spinner__pointer" aria-hidden="true" />
      <svg class="spinner__wheel" viewBox="0 0 200 200" role="img" aria-label="Restaurant wheel">
        <g
          class="spinner__rotor"
          :style="{ transform: `rotate(${rotation}deg)` }"
          @transitionend="onTransitionEnd"
        >
          <g
            v-for="seg in segments"
            :key="seg.name"
            class="spinner__seg"
            :class="{ 'spinner__seg--dim': winnerIndex !== null && seg.index !== winnerIndex }"
          >
            <path :d="seg.path" :fill="seg.color" stroke="var(--surface-app)" stroke-width="1" />
            <text
              :x="seg.lx"
              :y="seg.ly"
              class="spinner__label"
              text-anchor="middle"
              dominant-baseline="middle"
            >
              {{ seg.label }}
            </text>
          </g>
        </g>
        <!-- Outer rim + hub (static, drawn over the rotor) frame the wheel. -->
        <circle :cx="CENTER" :cy="CENTER" r="93" fill="none" stroke="var(--border-subtle)" stroke-width="2" />
        <circle :cx="CENTER" :cy="CENTER" r="10" fill="var(--surface-raised)" stroke="var(--border-strong)" stroke-width="1.5" />
        <circle :cx="CENTER" :cy="CENTER" r="3.5" fill="var(--accent-7)" />
      </svg>
    </div>

    <div class="spinner__controls">
      <Button variant="primary" :disabled="!canSpin" :loading="spinning" @click="spin">Spin</Button>
      <p v-if="result" class="spinner__result">
        <span class="spinner__result-tag">Winner</span>
        <span class="spinner__result-name">{{ result }}</span>
      </p>
      <p v-else-if="names.length < 2" class="spinner__hint">Add at least 2 restaurants to spin.</p>
    </div>
  </div>
</template>

<style scoped>
.spinner {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: var(--space-5);
}

.spinner__wheel-wrap {
  position: relative;
  width: 280px;
  max-width: 100%;
}

.spinner__wheel {
  display: block;
  width: 100%;
  height: auto;
  filter: drop-shadow(0 4px 14px rgba(0, 0, 0, 0.12));
}

.spinner__rotor {
  transform-origin: 100px 100px;
  transition: transform 3.2s cubic-bezier(0.16, 1, 0.3, 1);
}

/* After the wheel settles, fade the losing segments so the winner under the pointer stands out. */
.spinner__seg {
  transition: opacity 0.35s var(--ease-standard);
}

.spinner__seg--dim {
  opacity: 0.3;
}

.spinner__label {
  font-family: var(--font-body);
  font-size: 7px;
  font-weight: var(--weight-semibold);
  fill: var(--text-on-accent);
}

.spinner__pointer {
  position: absolute;
  top: -2px;
  left: 50%;
  z-index: 1;
  width: 0;
  height: 0;
  transform: translateX(-50%);
  border-right: 8px solid transparent;
  border-left: 8px solid transparent;
  border-top: 14px solid var(--text-primary);
}

.spinner__controls {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: var(--space-2);
}

.spinner__result {
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
  margin: 0;
}

.spinner__result-tag {
  padding: 2px var(--space-2);
  font-family: var(--font-body);
  font-size: var(--text-xs);
  font-weight: var(--weight-semibold);
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--text-on-accent);
  background: var(--accent-7);
  border-radius: var(--radius-full);
}

.spinner__result-name {
  font-family: var(--font-display);
  font-size: var(--text-lg);
  font-weight: var(--weight-semibold);
  color: var(--text-primary);
}

.spinner__hint {
  margin: 0;
  font-size: var(--text-sm);
  color: var(--text-secondary);
}
</style>
